name: Python Test

on: push

jobs:
  build:
    strategy:
      matrix:
        python: ['3.6','3.7']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} ( ${{ matrix.os }} )
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Setup Python test
        run: pip install ".[develop]"
      - name: Run test
        run: pytest tests -v --durations=5 --lf
