name: Python Test

on: push

jobs:
  build:
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8']
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} ( ${{ matrix.os }} )
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install poetry
        run: pip install poetry
      - name: Setup Python test
        run: make install-dev
      - name: Run test
        run: make test-detail
